### ISSUE TITLE
Секция "Мы лучшие"

### ISSUE THREAD

**Issue by igosheva** [IsaevAlexandr/Loftschool-second-task#9]
section-title_color_black -  не допустимый нейминг по БЭМ. Можно только один модификатор к элементу, т.е. максимум section-title_color или section-title_black

**Comment by igosheva** [comment]
benefits__list - элемент относится к блоку benefits, которого на странице нет

**Comment by igosheva** [comment]
http://joxi.ru/Q2KB6Qji9yzbPm - выровнять в мобильной версии текст - должен быть на одном уровне во всех карточках

**Comment by IsaevAlexandr** [comment]
done
